apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-base-config
  namespace: flask-base
data:
  FLASK_ENV: production
  PREFERRED_URL_SCHEME: https
  TRUST_PROXY_HEADERS: "true"
  SERVER_NAME: flask.example.com
  SAML_SP_ENTITY_ID: https://flask.example.com/auth/saml/metadata
  SAML_SP_ACS_URL: https://flask.example.com/auth/saml/acs
  SAML_SP_SLS_URL: https://flask.example.com/auth/saml/sls
  SAML_IDP_ENTITY_ID: https://idp.example.com/metadata
  SAML_IDP_SSO_URL: https://idp.example.com/sso
  SAML_IDP_SLO_URL: https://idp.example.com/slo
