apiVersion: v1
kind: Secret
metadata:
  name: flask-base-secret
  namespace: flask-base
type: Opaque
stringData:
  SECRET_KEY: replace-with-a-long-random-value
  SCIM_BEARER_TOKEN: replace-with-a-long-random-scim-token
  DATABASE_URL: postgresql+psycopg://flask_user:flask_password@postgres:5432/flask_base
  SAML_IDP_X509_CERT: |
    -----BEGIN CERTIFICATE-----
    replace-me
    -----END CERTIFICATE-----
